#spring.application.name=demo
spring.application.name=WalletApp


# H2 setup
#spring.datasource.url=jdbc:h2:mem:testdb

#spring.datasource.url=jdbc:postgresql://db.bpjajpidyksidhjwdsxt.supabase.co:5432/postgres?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=Bhimaharsha%401984
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#
## hibernate setup
## Keep generated tables when the application stops.
#spring.jpa.hibernate.ddl-auto = update
##spring.jpa.hibernate.ddl-auto = validate
##spring.jpa.hibernate.ddl-auto = none
##spring.jpa.open-in-view = false
#
#
#spring.jpa.show-sql=true


spring.cloud.gcp.project-id=cybernetic-pact-417810

spring.cloud.gcp.sql.enabled=true
spring.cloud.gcp.sql.instance-connection-name=cybernetic-pact-417810:asia-south1:somesh-postgres-db
spring.cloud.gcp.sql.database-name=wallet-app
spring.datasource.username=demo-user1
spring.datasource.password=(|Dtmr5@-IJ9run=

# Optional: use PRIVATE for a private-IP Cloud SQL instance
spring.cloud.gcp.sql.ip-types=PUBLIC

# For initial development only
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true